# See https://pre-commit.com for more information
default_stages: [pre-commit, pre-push]
default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v5.0.0'
    hooks:
      - id: check-added-large-files
        exclude: ^tests/fixtures/
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: ^demo-data/pickers/

  - repo: https://github.com/pycqa/isort
    rev: '6.0.1'
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length=88']

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ['--line-length=88']

  - repo: https://github.com/hadialqattan/pycln
    rev: 'v2.5.0'
    hooks:
      - id: pycln
        args: [--all]

  - repo: https://github.com/pycqa/flake8
    rev: '7.3.0'
    hooks:
      - id: flake8
        args: [--enable-extensions=T001]
        additional_dependencies:
          - flake8-bugbear==22.12.6
          - flake8-docstrings==1.6.0
          - flake8-import-order==0.18.2
          - pep8-naming==0.13.2
          - flake8-print==5.0.0

  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.20.0'
    hooks:
      - id: pyupgrade
        args: ['--py38-plus']

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 'v1.10.0'
    hooks:
      - id: python-no-log-warn
      - id: python-no-eval
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.17.0'
    hooks:
      - id: mypy
        exclude: ^alembic/
        args: ["--cache-dir", ".mypy_cache"]
        additional_dependencies:
          - sqlalchemy==2.0.41
          - types-python-dateutil==2.8.19.4
          - types-requests==2.28.11.5

  - repo: https://github.com/PyCQA/bandit
    rev: '1.8.6'
    hooks:
      - id: bandit
        args: [ '-lll' ]  # highest severity
        exclude: ^alembic/
