"""Add bak test trade and runner models

Revision ID: 569df8fd1a46
Revises: cbf5964bc08f
Create Date: 2025-09-01 15:45:07.306552

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "569df8fd1a46"
down_revision: Union[str, Sequence[str], None] = "cbf5964bc08f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_run",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("strategy_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "backtest_config_data", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        op.f("ix_backtest_run_backtest_config_data"),
        "backtest_run",
        ["backtest_config_data"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_run_started_at"), "backtest_run", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_backtest_run_strategy_id"),
        "backtest_run",
        ["strategy_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backtest_run_strategy_id"), table_name="backtest_run")
    op.drop_index(op.f("ix_backtest_run_started_at"), table_name="backtest_run")
    op.drop_index(
        op.f("ix_backtest_run_backtest_config_data"), table_name="backtest_run"
    )
    op.drop_table("backtest_run")
    # ### end Alembic commands ###
