"""intial migration script to create all stock index, security and ohlcv tables

Revision ID: 7176b84e4f08
Revises:
Create Date: 2025-07-22 14:27:04.753688

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7176b84e4f08"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gics_sector", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "gics_sub_industry", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("cik", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_security_cik"), "security", ["cik"], unique=False)
    op.create_index(op.f("ix_security_symbol"), "security", ["symbol"], unique=False)
    op.create_table(
        "stock_index_snapshot",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("index_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("snapshot_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_index_snapshot_index_name"),
        "stock_index_snapshot",
        ["index_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_index_snapshot_snapshot_date"),
        "stock_index_snapshot",
        ["snapshot_date"],
        unique=False,
    )
    op.create_table(
        "ohlcv_daily",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("candle_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("high", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("low", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("close", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candle_date", "security_id", name="uq_ohlcv_daily_date_security"
        ),
    )
    op.create_index(
        op.f("ix_ohlcv_daily_candle_date"), "ohlcv_daily", ["candle_date"], unique=False
    )
    op.create_index(
        op.f("ix_ohlcv_daily_security_id"), "ohlcv_daily", ["security_id"], unique=False
    )
    op.create_table(
        "stock_index_constituent",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("index_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["stock_index_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_id", "security_id", name="uq_constituent_snapshot_security"
        ),
    )
    op.create_index(
        op.f("ix_stock_index_constituent_index_name"),
        "stock_index_constituent",
        ["index_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_index_constituent_index_name"),
        table_name="stock_index_constituent",
    )
    op.drop_table("stock_index_constituent")
    op.drop_index(op.f("ix_ohlcv_daily_security_id"), table_name="ohlcv_daily")
    op.drop_index(op.f("ix_ohlcv_daily_candle_date"), table_name="ohlcv_daily")
    op.drop_table("ohlcv_daily")
    op.drop_index(
        op.f("ix_stock_index_snapshot_snapshot_date"), table_name="stock_index_snapshot"
    )
    op.drop_index(
        op.f("ix_stock_index_snapshot_index_name"), table_name="stock_index_snapshot"
    )
    op.drop_table("stock_index_snapshot")
    op.drop_index(op.f("ix_security_symbol"), table_name="security")
    op.drop_index(op.f("ix_security_cik"), table_name="security")
    op.drop_table("security")
    # ### end Alembic commands ###
