"""rename strategy_id -> signal_strategy_id on backtest_trade, add execution_strategy_id

Revision ID: d36b178b9d53
Revises: 10fb02b2f344
Create Date: 2025-09-05 13:51:43.023302

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d36b178b9d53"
down_revision: Union[str, Sequence[str], None] = "10fb02b2f344"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "backtest_trade",
        sa.Column(
            "execution_strategy_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.create_index(
        op.f("ix_backtest_trade_execution_strategy_id"),
        "backtest_trade",
        ["execution_strategy_id"],
        unique=False,
    )

    op.execute(
        f"UPDATE {'backtest_trade'} SET execution_strategy_id = 'exec_current_defaults_v0' "
        "WHERE execution_strategy_id IS NULL"
    )

    # switch to nullable false
    with op.batch_alter_table("backtest_trade") as batch_op:
        batch_op.alter_column(
            "execution_strategy_id",
            existing_type=sa.String(),
            nullable=False,
            server_default=None,
        )

    op.alter_column(
        "backtest_trade",
        "strategy_id",
        new_column_name="signal_strategy_id",
        existing_type=sa.String(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_backtest_trade_execution_strategy_id"), table_name="backtest_trade"
    )
    op.drop_column("backtest_trade", "execution_strategy_id")

    op.alter_column(
        "backtest_trade",
        "signal_strategy_id",
        new_column_name="strategy_id",
    )
    # ### end Alembic commands ###
