"""drop duplicate snapshot_date from index_constituent

Revision ID: 21db97d959ec
Revises: c8535df47fd1
Create Date: 2025-07-21 16:14:27.798443

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21db97d959ec"
down_revision: Union[str, Sequence[str], None] = "c8535df47fd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_index_constituent_snapshot_date"), table_name="index_constituent"
    )
    op.drop_column("index_constituent", "snapshot_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ohlcv_daily",
        "volume",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.add_column(
        "index_constituent",
        sa.Column("snapshot_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_index_constituent_snapshot_date"),
        "index_constituent",
        ["snapshot_date"],
        unique=False,
    )
    # ### end Alembic commands ###
