"""add new technical indicator columns

Revision ID: d631858e0aad
Revises: cc1fc9133a6b
Create Date: 2025-10-31 12:06:19.268611

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d631858e0aad"
down_revision: Union[str, Sequence[str], None] = "cc1fc9133a6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "technical_indicator", sa.Column("avg_vol_5d", sa.Float(), nullable=True)
    )
    op.add_column(
        "technical_indicator", sa.Column("avg_vol_50d", sa.Float(), nullable=True)
    )
    op.add_column(
        "technical_indicator",
        sa.Column("avg_vol_weighted_change_5d", sa.Float(), nullable=True),
    )
    op.add_column(
        "technical_indicator",
        sa.Column("avg_vol_weighted_change_50d", sa.Float(), nullable=True),
    )
    op.add_column(
        "technical_indicator",
        sa.Column("price_volume_corr_20", sa.Float(), nullable=True),
    )
    op.add_column(
        "technical_indicator", sa.Column("percent_change", sa.Float(), nullable=True)
    )
    op.add_column(
        "technical_indicator", sa.Column("range_pct_20", sa.Float(), nullable=True)
    )
    op.add_column(
        "technical_indicator",
        sa.Column("breakout_proximity_20", sa.Float(), nullable=True),
    )
    op.add_column(
        "technical_indicator",
        sa.Column("rolling_volatility_20", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("technical_indicator", "rolling_volatility_20")
    op.drop_column("technical_indicator", "breakout_proximity_20")
    op.drop_column("technical_indicator", "range_pct_20")
    op.drop_column("technical_indicator", "percent_change")
    op.drop_column("technical_indicator", "price_volume_corr_20")
    op.drop_column("technical_indicator", "avg_vol_weighted_change_50d")
    op.drop_column("technical_indicator", "avg_vol_weighted_change_5d")
    op.drop_column("technical_indicator", "avg_vol_50d")
    op.drop_column("technical_indicator", "avg_vol_5d")
    # ### end Alembic commands ###
