"""Add ohlcv_daily table

Revision ID: c8535df47fd1
Revises: 6145b04d3763
Create Date: 2025-07-21 16:09:50.941268

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8535df47fd1"
down_revision: Union[str, Sequence[str], None] = "6145b04d3763"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ohlcv_daily",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("candle_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("high", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("low", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("close", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("adjusted_close", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "candle_date", "security_id", name="uq_ohlcv_daily_date_security"
        ),
    )
    op.create_index(
        op.f("ix_ohlcv_daily_candle_date"), "ohlcv_daily", ["candle_date"], unique=False
    )
    op.create_index(
        op.f("ix_ohlcv_daily_security_id"), "ohlcv_daily", ["security_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ohlcv_daily_security_id"), table_name="ohlcv_daily")
    op.drop_index(op.f("ix_ohlcv_daily_candle_date"), table_name="ohlcv_daily")
    op.drop_table("ohlcv_daily")
    # ### end Alembic commands ###
