"""Add unique constraint

Revision ID: 64a53d31e67d
Revises: 755366b87e83
Create Date: 2025-07-17 17:16:56.115631

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64a53d31e67d"
down_revision: Union[str, Sequence[str], None] = "755366b87e83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_index_constituent_daily",
        "indexconstituent",
        ["index_name", "symbol", "snapshot_date"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_index_constituent_daily", "indexconstituent", type_="unique")
    # ### end Alembic commands ###
