"""add metadata fields to security table

Revision ID: 776a788e56c7
Revises: 267e9278ad28
Create Date: 2025-08-03 14:05:06.410596

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "776a788e56c7"
down_revision: Union[str, Sequence[str], None] = "267e9278ad28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("security", sa.Column("first_trade_date", sa.Date(), nullable=True))
    op.add_column(
        "security",
        sa.Column("exchange", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("security", "exchange")
    op.drop_column("security", "first_trade_date")
    # ### end Alembic commands ###
