"""add eod_signal table for persisting signals

Revision ID: 2b4e0b2b01dd
Revises: 776a788e56c7
Create Date: 2025-08-09 14:19:20.003791

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b4e0b2b01dd"
down_revision: Union[str, Sequence[str], None] = "776a788e56c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "eod_signal",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("signal_date", sa.Date(), nullable=False),
        sa.Column("strategy_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("ohlcv_daily_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint("score >= 0.0 AND score <= 1.0", name="ck_score_range"),
        sa.ForeignKeyConstraint(
            ["ohlcv_daily_id"],
            ["ohlcv_daily.id"],
        ),
        sa.ForeignKeyConstraint(
            ["security_id", "signal_date"],
            ["technical_indicator.security_id", "technical_indicator.measurement_date"],
            name="fk_eod_signal_technical_indicator",
            onupdate="RESTRICT",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["security.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "signal_date",
            "strategy_name",
            "security_id",
            name="uq_one_result_per_strategy_and_security",
        ),
    )
    op.create_index(
        op.f("ix_eod_signal_security_id"), "eod_signal", ["security_id"], unique=False
    )
    op.create_index(
        op.f("ix_eod_signal_signal_date"), "eod_signal", ["signal_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_eod_signal_signal_date"), table_name="eod_signal")
    op.drop_index(op.f("ix_eod_signal_security_id"), table_name="eod_signal")
    op.drop_table("eod_signal")
    # ### end Alembic commands ###
