"""Add back test trade model

Revision ID: 10fb02b2f344
Revises: 569df8fd1a46
Create Date: 2025-09-02 16:14:43.402206

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10fb02b2f344"
down_revision: Union[str, Sequence[str], None] = "569df8fd1a46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_trade",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("eod_signal_id", sa.Integer(), nullable=False),
        sa.Column("strategy_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("exit_date", sa.Date(), nullable=False),
        sa.Column(
            "exit_reason",
            sa.Enum("stop", "target", "time_stop", name="exitreason"),
            nullable=False,
        ),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("exit_price", sa.Float(), nullable=False),
        sa.Column("stop_price", sa.Float(), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=False),
        sa.Column("atr_used", sa.Float(), nullable=False),
        sa.Column("pnl_percent", sa.Float(), nullable=False),
        sa.Column("r_multiple", sa.Float(), nullable=False),
        sa.Column("bars_held", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["eod_signal_id"],
            ["eod_signal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "eod_signal_id", name="uq_backtest_trade_run_signal"
        ),
    )
    op.create_index(
        op.f("ix_backtest_trade_entry_date"),
        "backtest_trade",
        ["entry_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_trade_eod_signal_id"),
        "backtest_trade",
        ["eod_signal_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_trade_exit_date"),
        "backtest_trade",
        ["exit_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_trade_run_id"), "backtest_trade", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_backtest_trade_security_id"),
        "backtest_trade",
        ["security_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backtest_trade_strategy_id"),
        "backtest_trade",
        ["strategy_id"],
        unique=False,
    )

    op.alter_column(
        "backtest_run",
        "backtest_config_data",
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using="backtest_config_data::jsonb",
    )

    op.drop_index(
        op.f("ix_backtest_run_backtest_config_data"), table_name="backtest_run"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_backtest_run_backtest_config_data"),
        "backtest_run",
        ["backtest_config_data"],
        unique=False,
    )
    op.alter_column(
        "backtest_run",
        "backtest_config_data",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_backtest_trade_strategy_id"), table_name="backtest_trade")
    op.drop_index(op.f("ix_backtest_trade_security_id"), table_name="backtest_trade")
    op.drop_index(op.f("ix_backtest_trade_run_id"), table_name="backtest_trade")
    op.drop_index(op.f("ix_backtest_trade_exit_date"), table_name="backtest_trade")
    op.drop_index(op.f("ix_backtest_trade_eod_signal_id"), table_name="backtest_trade")
    op.drop_index(op.f("ix_backtest_trade_entry_date"), table_name="backtest_trade")
    op.drop_table("backtest_trade")
    # ### end Alembic commands ###
