"""Add index constituent table and snapshot

Revision ID: 2f629b39802c
Revises:
Create Date: 2025-07-19 14:44:51.130914

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f629b39802c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_constituent",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("index_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("company_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("gics_sector", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "gics_sub_industry", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("cik", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "index_name", "symbol", "snapshot_date", name="uq_index_constituent_daily"
        ),
    )
    op.create_index(
        op.f("ix_index_constituent_cik"), "index_constituent", ["cik"], unique=False
    )
    op.create_index(
        op.f("ix_index_constituent_index_name"),
        "index_constituent",
        ["index_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_index_constituent_snapshot_date"),
        "index_constituent",
        ["snapshot_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_index_constituent_symbol"),
        "index_constituent",
        ["symbol"],
        unique=False,
    )
    op.create_table(
        "index_snapshot",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("index_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("snapshot_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_index_snapshot_index_name"),
        "index_snapshot",
        ["index_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_index_snapshot_snapshot_date"),
        "index_snapshot",
        ["snapshot_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_index_snapshot_snapshot_date"), table_name="index_snapshot")
    op.drop_index(op.f("ix_index_snapshot_index_name"), table_name="index_snapshot")
    op.drop_table("index_snapshot")
    op.drop_index(op.f("ix_index_constituent_symbol"), table_name="index_constituent")
    op.drop_index(
        op.f("ix_index_constituent_snapshot_date"), table_name="index_constituent"
    )
    op.drop_index(
        op.f("ix_index_constituent_index_name"), table_name="index_constituent"
    )
    op.drop_index(op.f("ix_index_constituent_cik"), table_name="index_constituent")
    op.drop_table("index_constituent")
    # ### end Alembic commands ###
