"""add symbol constraint to securities

Revision ID: cc1fc9133a6b
Revises: 53664280e60e
Create Date: 2025-09-11 09:02:30.890959

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc1fc9133a6b"
down_revision: Union[str, Sequence[str], None] = "53664280e60e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_security_symbol", "security", ["symbol"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_security_symbol", "security", type_="unique")
    # ### end Alembic commands ###
